### ISSUE TITLE
[v0.26] - undefined method `setup` for Decidim::Devise:Module

### ISSUE THREAD

**Issue by Quentinchampenois** [OpenSourcePolitics/decidim-app#109]
#### Description

On version `0.26`, an error occurs when application is initialised, raised at `decidim-core/lib/decidim/core/engine.rb:570`.
It seems there is a context issue where the class `Devise` is interpreted as in part of module `Decidim`.

#### Step to reproduce
* `bundle exec rake db:seed --trace`
* An error should occur

#### Stacktrace

```
** Invoke db:schema:load (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `setup' for Decidim::Devise:Module
/Users/quentinchampenois/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-8ad4ad8f4104/decidim-core/lib/decidim/core/engine.rb:570:in `block in <class:Engine>'
/Users/quentinchampenois/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:32:in `instance_exec'
/Users/quentinchampenois/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:32:in `run'
/Users/quentinchampenois/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:61:in `block in run_initializers'
```

#### More informations

The `development_app` is successfully generated with the generator

**Comment by Quentinchampenois** [comment]
Fixed on `rc/0.26` by commit [d41f6f7](https://github.com/OpenSourcePolitics/decidim-app/commit/d41f6f76654ab7f685908fda4775b59550a61dbb)
